apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  database-url: {{ .Values.postgres.databaseUrl | b64enc | quote }}
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
